# NumPy Упражнения

Теперь, когда мы узнали о NumPy, давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы более сложные вопросы.

#### Импорт NumPy как np

#### Создание массива из 10 нулей

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Создайте массив из 10 единиц

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Создайте массив из 10 пятерок

#### Создадим массив целых чисел от 10 до 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Создадим массив из всех четных целых чисел от 10 до 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Создание матрицы 3x3 со значениями в диапазоне от 0 до 8¶

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### Создание единичной матрицы 3x3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Используйте NumPy для генерации случайного числа от 0 до 1

array([ 0.93645765])

#### Используйте NumPy для создания массива из 25 случайных чисел, отобранных из стандартного нормального распределения

array([ 0.96447606,  0.58595639, -0.24102021, -0.01972777,  0.19623981,
       -1.36104766, -0.99439269,  0.88758827, -1.08932569,  0.52450315,
       -0.58393132, -0.79123987,  0.07177192, -1.95609962,  1.00678034,
        0.43673244, -1.40132582, -0.96302038, -0.52134657, -0.41309678,
       -1.90590993, -0.13940084, -0.73902137,  1.09009097, -1.16131202])

#### Создайте матрицу 10 на 10 из равномерно удаленных точек от 0.1 до 1( см linspace):

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Создайте массив из 20 линейно удаленных точек от 0 до 1( см linspace):

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Индексы

В матрице

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Напишите код таким образом, чтоб появился вывод на экран

In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код



In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код



In [ ]:
# выведите

20

In [ ]:
# впишите код



In [ ]:
# выведите

20

In [ ]:
# впишите код
# отличный от кода выше



In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[21, 22, 23, 24, 25]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([21, 22, 23, 24, 25])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код






In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код





### Теперь сделайте следующее

#### Получить сумму всех значений в mat

325

#### Получить стандартное отклонение значений в mat (пакет Статистика)

#### Посчитайте сумму всех столбцов в mat